// 1) GREQ FUNCTION VORN STANUMA MEK DATARK ARRAY ARGUMETN EV MEK TIV ORINAK 5 EV
// RECURSIAI MIJOCOV AMEN KANCHI ZHAMANAK ARRAYI MEJ LCREQ 1 TIV@ MINCHEV ARRAYI ERKARUTYUN@ DARNA 3
//
// ===================ANSWER===================

//2) RECURSIAI MIJOCOV HASHVEQ TRVAC TVI FAKTORIAL@
// 5 ---> 1 * 2 * 3 * 4 * 5

// ===================ANSWER===================






